version: '3'
services:
    cf-simplefile-server:
        build: ./californium
        volumes:
            - './passwd:/data/passwd'
        command: java -jar /californium/demo-apps/cf-simplefile-server/target/cf-simplefile-server-2.3.0-SNAPSHOT.jar

    gw:
        image: 'jeanblanchard/busybox-java'
        ports:
                - '8080:8080'
                - '5683:5683'
                - '5684:5684'
        volumes:
            - '.:/app'
        command:    java -jar /app/leshan-server-demo.jar

    anjay:
        depends_on:
            - 'gw'
        build: ./anjay
        command: /Anjay/output/bin/demo -t -u coap://gw:5683
