version: '3'
services:
    gw:
        image: 'jeanblanchard/busybox-java'
        ports:
                - '8080:8080'
                - '5683:5683'
                - '5684:5684'
        volumes:
            - '.:/app'
        command:    java -jar /app/leshan-server-demo.jar

    anjay:
        depends_on:
            - 'gw'
        build: ./anjay
        command: /Anjay/output/bin/demo -t -u coap://gw:5683
